---
# ╔═════════════════════════════════╗
# ║ Intended to run on Ubuntu 24.04 ║
# ╚═════════════════════════════════╝
- name: Configure pc
  hosts: localhost
  connection: local

  vars_files:
    - ./config.yml
    - ./dotfiles-personal/vars.yml

  pre_tasks:
    - name: Ensure /usr/local/bin exists
      file:
        dest: /usr/local/bin
        state: directory
        mode: 0755

  tasks:
    - import_role:
        name: system
      tags: [system]
    - import_role:
        name: geerlingguy.docker
      become: true
      when: not vm
      tags: [docker]
      vars:
        docker_daemon_options:
          bip: "172.20.0.1/24"
          data-root: "/docker"
          default-address-pools:
            - base: 172.20.0.0/16
              size: 24
    - import_role:
        name: software
      tags: [software]
