---
- name: build dmenu
  become: true
  shell: "{{ home }}/.bin/_build_flexipatch dmenu"
  args:
    chdir: home/.config/dmenu
  register: dmenu
  changed_when: dmenu.stdout is search("c99 -o") or dmenu.stdout is search("cc -o")

