---
- name: build dmenu
  become: true
  shell: FLEXIPATCH=dmenu ./run.sh
  args:
    chdir: home/.config/dmenu
  register: dmenu
  changed_when: dmenu.stdout is search("c99 -o") or dmenu.stdout is search("cc -o")

