---
- name: "Create {{ dotfiles_data_dir }}"
  become: true
  file:
    path: "{{ dotfiles_data_dir }}"
    state: directory
    mode: 0755
    group: root
    owner: root

- name: "Clone luastatus repo"
  become: true
  git:
    repo: https://github.com/shdown/luastatus
    dest: "{{ dotfiles_data_dir }}/luastatus"
    version: 99123f6613332631fbfd2a11c2f32f0854e19d3d
    depth: 1
    update: yes
  register: clone_luastatus

- name: build luastatus
  become: true
  when: clone_luastatus.changed
  command: "cmake ."
  args:
    chdir: "{{ dotfiles_data_dir }}/luastatus"
  changed_when: false

- name: build luastatus
  become: true
  when: clone_luastatus.changed
  command: "make"
  args:
    chdir: "{{ dotfiles_data_dir }}/luastatus"
  changed_when: false

- name: build luastatus
  become: true
  when: clone_luastatus.changed
  command: "make install"
  args:
    chdir: "{{ dotfiles_data_dir }}/luastatus"
  changed_when: false
