#!/usr/bin/env bash

pulsemixer --unmute

redshift -PO 6500

nmcli networking on

feh --no-fehbg --bg-fill ~/.config/wallpapers/wallhaven-jxlwpm-eclipse.jpg

notify-send "Good morning!"
echo "Good morning!"
