#!/usr/bin/env bash

# Directories
dwm_dir="$HOME/.config/themes/dwm"
dmenu_dir="$HOME/.config/themes/dmenu"
luastatus_dir="$HOME/.config/themes/luastatus"
zathura_dir="$HOME/.config/zathura"

prompt="dmenu -l 9 "

# Theme
cancel="窱 Cancel"
theme1=" Cozy-Night"
theme2=" Dracula"
theme3=" Gruvbox"
theme4=" Nord"

# Variable to pass to dmenu or rofi
option="$cancel\n$theme1\n$theme2\n$theme3\n$theme4"

theme_change()
{
	cp ${dwm_dir}/$1 ${dwm_dir}/theme
	cp ${dmenu_dir}/$1 ${dmenu_dir}/theme
	cp ${luastatus_dir}/$1.lua ${luastatus_dir}/color.lua
	# cp ${zathura_dir}/theme/$1 ${zathura_dir}/theme.color

	xrdb -merge -I$HOME ~/.Xresources # reload Xresources

    # calls xrdb function in dwm
    xsetroot -name "fsignal:2"
    # reset luastatus (statusbar_wrapper restarts it)
    kill -9 $(pidof luastatus)
}

select="$(echo -e "$option" | $prompt -p "Choose a theme: " )"
case $select in
	$theme1)
		feh --bg-fill $HOME/.config/wallpapers/pixelart_night_train_cozy_gas.png
		theme_change cozy-night
		;;
	$theme2)
		feh --bg-fill $HOME/.config/wallpapers/pixelart_arabian_palace_princess.png
		theme_change dracula
		;;
	$theme3)
		feh --bg-fill $HOME/.config/wallpapers/pixelart_house_inside_girl_book_dog.png
		theme_change gruvbox
        ;;
	$theme4)
		feh --bg-fill $HOME/.config/wallpapers/pixelart_medicine_flower_reminder_nord.png
		theme_change nord
		;;
esac
