---
##====================================== PREFS ========================================##
#########################################################################################

- name: Set custom apt preferences
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/custom.pref
    content: |
      Explanation: Prevent installation of snapd
      Package: snapd
      Pin: release a=*
      Pin-Priority: -10

      Explanation: Prevent installation of ubuntu-desktop-minimal
      Package: ubuntu-desktop-minimal
      Pin: release a=*
      Pin-Priority: -10

      Explanation: Prevent installation of ubuntu-desktop
      Package: ubuntu-desktop
      Pin: release a=*
      Pin-Priority: -10

      Explanation: Prevent installation of gdm3
      Package: gdm3
      Pin: release a=*
      Pin-Priority: -10

##====================================== REPOS ========================================##
#########################################################################################
# examples of new format: https://gist.github.com/roib20/27fde10af195cee1c1f8ac5f68be7e9b

# - name: Add spotify apt repository
#   become: true
#   ansible.builtin.deb822_repository:
#     name: spotify
#     types: [deb]
#     uris:
#       - http://repository.spotify.com
#     signed_by: https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg
#     suites: [stable]
#     components: [non-free]
#     state: present
#     architectures: amd64
#     enabled: yes

- name: Add google apt repository
  become: true
  ansible.builtin.deb822_repository:
    name: google
    types: [deb]
    uris:
      - http://dl.google.com/linux/chrome/deb
      - http://dl.google.com/linux/earth/deb
    signed_by: https://dl.google.com/linux/linux_signing_key.pub
    suites: [stable]
    components: [main]
    state: present
    architectures: amd64
    enabled: yes

# https://support.yubico.com/hc/en-us/articles/360016649039-Installing-Yubico-Software-on-Linux
- name: Add yubico apt repository
  become: true
  ansible.builtin.deb822_repository:
    name: yubico
    types: [deb]
    uris:
      - http://ppa.launchpad.net/yubico/stable/ubuntu
    signed_by: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3653E21064B19D134466702E43D5C49532CBA1A9
    suites: [lunar]
    components: [main]
    state: present
    architectures: amd64
    enabled: yes
  changed_when: false # keyserver.ubuntu.com returns key metadata in random order

- name: Add mozilla apt repository
  become: true
  ansible.builtin.deb822_repository:
    name: mozilla
    types: [deb]
    uris:
      - http://ppa.launchpad.net/mozillateam/ppa/ubuntu
    signed_by: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x0AB215679C571D1C8325275B9BDB3D89CE49EC21
    suites: [lunar]
    components: [main]
    state: present
    architectures: amd64
    enabled: yes
  changed_when: false # keyserver.ubuntu.com returns key metadata in random order

- name: Add Lens Desktop repository
  become: true
  ansible.builtin.deb822_repository:
    name: lens
    types: [deb]
    uris:
      - https://downloads.k8slens.dev/apt/debian
    signed_by: https://downloads.k8slens.dev/keys/gpg
    suites: [stable]
    components: [main]
    state: present
    architectures: amd64
    enabled: yes

##==================================== PACKAGES =======================================##
#########################################################################################

- name: Install some packages
  become: true
  apt:
    state: present
    install_recommends: false
    name:
      - age
      - autorandr
      - bluez
      - bluez-alsa-utils
      - bridge-utils
      - build-essential
      - cmake
      - cmatrix
      - curl
      - dbus
      - dnsutils
      - dunst
      - expect
      - fd-find
      - feh
      - firmware-sof-signed # audio
      - flameshot
      - flatpak
      - fzf
      - gimp
      - gir1.2-nm-1.0
      - gir1.2-spiceclientgtk-3.0
      - gnupg
      - google-chrome-stable
      - htop
      - intel-media-va-driver-non-free 
      - jq
      - libasound2-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libharfbuzz-dev
      - libimlib2-dev
      - liblua5.1-0-dev
      - libnl-3-dev
      - libnl-genl-3-dev
      - libpam-yubico
      - libpam0g-dev
      - libtool
      - libudev-dev
      - libvirt-clients
      - libvirt-daemon-system
      - libx11-dev
      - libx11-xcb-dev
      - libxcb-ewmh-dev
      - libxcb-icccm4-dev
      - libxcb-res0-dev
      - libxcb-xrm-dev
      - libxft-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxrender-dev
      - libyajl-dev
      - libyubikey-udev
      - libyubikey0
      - lua5.1
      - luarocks
      - lxrandr
      - mdp
      - moreutils
      - mpv
      - ncal
      - neofetch
      - net-tools
      - network-manager-gnome
      - openjdk-17-jdk
      - openjdk-21-jdk
      - openvpn-systemd-resolved
      - parallel
      - pcscd
      - picom
      - pinentry-qt
      - pkg-config
      - psmisc
      - pulseaudio-module-bluetooth
      - pulsemixer
      - python-is-python3
      - python3-docutils
      - python3-pip
      - python3-pynvim
      - python3.12-venv
      - qemu-kvm
      - ranger
      - redshift
      - ripgrep
      - rsync
      - rustup
      - sanoid
      - scdaemon
      - shellcheck
      - shfmt
      - software-properties-common
      - stow
      - sxhkd
      - sxiv
      - thunar
      - tmux
      - tree
      - ufw
      - unclutter
      - unzip
      - virt-manager
      - virt-manager
      - virtualenv
      - vlc
      - wpasupplicant # for wifi nic
      - xbindkeys
      - xcape
      - xcb
      - xclip
      - xdotool
      - xorg
      - xutils-dev
      - xvkbd
      - yubico-piv-tool
      - yubikey-manager
      - zathura

- name: Purge some packages
  become: true
  apt:
    state: absent
    purge: true
    autoremove: true
    name: 
      - gdm3
      - gedit-common
      - gir1.2-gdm-1.0 
      - gir1.2-gnomebluetooth-1.0
      - gir1.2-gnomedesktop-3.0
      - gir1.2-goa-1.0 
      - gnome-*
      - language-pack-gnome-*
      - language-pack-gnome-en-base
      - language-pack-gnome-ru 
      - language-selector-gnome
      - libgail18
      - libgnome-autoar-0-0
      - libgnome-bluetooth13 
      - libgnome-desktop-3-19
      - libgnome-games-support-1-3
      - libgnome-games-support-common 
      - libgnome-menu-3-0
      - libgnome-todo
      - libgnomekbd-common
      - libgnomekbd8
      - libgoa-1.0-0b 
      - libgoa-1.0-common
      - libpam-gnome-keyring
      - nautilus-extension-gnome-terminal
      - pinentry-gnome3
      - yaru-theme-gnome-shell
