#define ALPHA_PATCH 1
#define BOXDRAW_PATCH 1
#define CLIPBOARD_PATCH 1
#define COLUMNS_PATCH 1
#define CSI_22_23_PATCH 1
#define DELKEY_PATCH 1
#define EXTERNALPIPEIN_PATCH 1
#define LIGATURES_PATCH 1
#define NEWTERM_PATCH 1
#define SCROLLBACK_PATCH 1
// #define SCROLLBACK_MOUSE_PATCH 1
#define SCROLLBACK_MOUSE_ALTSCREEN_PATCH 1
#define SIXEL_PATCH 1
#define XRESOURCES_PATCH 1
#define XRESOURCES_RELOAD_PATCH 1
// #define FIXKEYBOARDINPUT_PATCH 1
