#!/bin/bash

# $1: app dir name
# $2: bin/*.sh launcher script name

# try to grab latest version; dunno if this actually works
idea_dir="$HOME/.local/share/JetBrains/Toolbox/apps/$1" 
if [ ! -d "$idea_dir" ]; then
    dunstify "$1 does not exist. Pls install via jetbrains-toolbox"
fi
_JAVA_AWT_WM_NONREPARENTING=1 nohup "$idea_dir/bin/$2" >/dev/null 2>&1 &
